spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: file
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://121.40.203.208:8761/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true